clone:
  depth: full
image: atlassian/default-image:3
pipelines:
  branches:
    master:
      - step:
          script:
            - ssh -V
            - git push --mirror git@github.com:Adalin-Labs/scoutflo-atlas-client.git
